site_name: Documentation Antaria
site_url: https://docs.antaria.ovh
site_description: Documentation officielle de la suite bureautique Antaria
site_author: Association Antaria

theme:
  name: material
  language: fr
  palette:
    # Mode clair
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer en mode sombre
    # Mode sombre
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer en mode clair
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Accueil: index.md
  - Guide utilisateur:
      - Démarrage rapide: guide/quick-start.md
      - Documents: guide/documents.md
      - Tableur: guide/spreadsheet.md
      - Présentation: guide/presentation.md
  - Documentation technique:
      - Architecture: tech/architecture.md
      - Installation: tech/installation.md
  - Premium:
      - Fonctionnalités: premium/features.md
      - Tarification: premium/pricing.md
  - À propos:
      - L'association: about/association.md
      - FAQ: about/faq.md
      - Contact: about/contact.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - attr_list
  - md_in_html

plugins:
  - search:
      lang: fr

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AntariaFR
    - icon: fontawesome/solid/envelope
      link: mailto:contact@antaria.ovh

copyright: Copyright &copy; 2025 Association Loi 1901 Antaria